### PR TITLE
KiCAD Files

### PR DESCRIPTION
**Pull request by nathanielhu**
Added the schematic files and set up the repo for KiCAD files

I'm a sick man.... I am a wicked man. An unattractive man. I think my liver hurts.

### CODE REVIEW

**Review by aldenhaase — DISMISSED** [review]

**Comment by aldenhaase** [comment]
🤯 2 million lines and 695 files? Putting in work 🦾 

Is this really all required?

**Comment by nathanielhu** [comment]
I think I need a new review thanks.

"There's a bypass over Holbrook now. Paid for with burgers no doubt.  I've lost count of all the cows. There'll be no salad sandwiches."

**Comment by nathanielhu** [comment]
> 🤯 2 million lines and 695 files? Putting in work 🦾
> 
> Is this really all required?

I included the libraries for the footprints and whatnot. We can go through and remove the unused ones but does it really matter?

**Comment by aldenhaase** [comment]
> > 🤯 2 million lines and 695 files? Putting in work 🦾
> > Is this really all required?
> 
> I included the libraries for the footprints and whatnot. We can go through and remove the unused ones but does it really matter?

Ideally we'll just have what is required for the project but maybe this is all required idk, seemed like a lot of files.

**Review by aldenhaase — APPROVED** [review]

**Comment by nathanielhu** [comment]
> > > 🤯 2 million lines and 695 files? Putting in work 🦾
> 
> > > Is this really all required?
> 
> > 
> 
> > I included the libraries for the footprints and whatnot. We can go through and remove the unused ones but does it really matter?
> 
> 
> 
> Ideally we'll just have what is required for the project but maybe this is all required idk, seemed like a lot of files.

It's not a lot of it is various switch layouts and whatnot but it's there's little harm in keeping them in. They can be removed when we finalize the PCB

**Pull request merged**
